import {
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
  Document,
  Footer,
  Header,
  LevelFormat,
  PageNumber,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

// Matches AKLA's own drafting convention (sampled from firm precedent/memo
// .docx files): Arial body text, 1" margins, justified paragraphs with a
// touch of "after" spacing, and legal-style decimal clause numbering
// (1. / 1.1. / 1.1.1.) generated by Word rather than typed by the AI.
//
// Pure module — no React. Used by the Draft panel of the AI Workspace for
// both its live "Preview as Word Document" tab and Save as Document Version.
const FIRM_FONT = "Arial";
const FIRM_BODY_SIZE = 22; // half-points -> 11pt
const FIRM_TITLE_SIZE = 28; // half-points -> 14pt
const FIRM_HEADER_FOOTER_SIZE = 16; // half-points -> 8pt
const FIRM_LINE_SPACING = { line: 252, lineRule: "auto" as const }; // ~1.05x
const FIRM_PARAGRAPH_SPACING_AFTER = 40; // dxa -> 2pt
const FIRM_NUMBERING_REFERENCE = "firm-clause-numbering";
const FIRM_NUMBERING_MAX_LEVEL = 3;

const firmNumberingConfig = {
  reference: FIRM_NUMBERING_REFERENCE,
  levels: Array.from({ length: FIRM_NUMBERING_MAX_LEVEL + 1 }, (_, level) => ({
    level,
    format: LevelFormat.DECIMAL,
    text: Array.from({ length: level + 1 }, (_, i) => `%${i + 1}`).join(".") + ".",
    alignment: AlignmentType.START,
    style: {
      run: { bold: true },
      paragraph: {
        indent: {
          left: convertInchesToTwip(0.5 + level * 0.25),
          hanging: convertInchesToTwip(0.25),
        },
      },
    },
  })),
};

interface InlineRunStyle {
  bold?: boolean;
  italics?: boolean;
  size?: number;
}

export interface PMNode {
  type: string;
  attrs?: Record<string, any>;
  content?: PMNode[];
  text?: string;
  marks?: { type: string }[];
}

// Runs off the live TipTap/ProseMirror editor JSON (editor.getJSON()) rather
// than the original AI markdown, so a lawyer's in-editor edits — including
// blank lines they left in place — are what actually gets exported.
function pmInlineRuns(nodes: PMNode[] | undefined, style: InlineRunStyle = {}): TextRun[] {
  if (!nodes) return [];
  const runs: TextRun[] = [];
  for (const node of nodes) {
    if (node.type === "hardBreak") {
      runs.push(new TextRun({ text: "", break: 1 }));
      continue;
    }
    if (node.type !== "text") continue;
    const marks = node.marks ?? [];
    const nodeStyle: InlineRunStyle = { ...style };
    if (marks.some((m) => m.type === "bold")) nodeStyle.bold = true;
    if (marks.some((m) => m.type === "italic")) nodeStyle.italics = true;
    const isCode = marks.some((m) => m.type === "code");
    runs.push(new TextRun({ text: node.text ?? "", font: isCode ? "Courier New" : FIRM_FONT, ...nodeStyle }));
  }
  return runs;
}

function pmListItems(items: PMNode[], level: number, paragraphs: Paragraph[]) {
  for (const item of items) {
    const nestedList = item.content?.find((n) => n.type === "bulletList" || n.type === "orderedList");
    const ownContent = (item.content ?? []).filter((n) => n.type !== "bulletList" && n.type !== "orderedList");
    const inline = ownContent.flatMap((n) => n.content ?? []);
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.JUSTIFIED,
        spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
        numbering: { reference: FIRM_NUMBERING_REFERENCE, level: Math.min(level, FIRM_NUMBERING_MAX_LEVEL) },
        children: pmInlineRuns(inline),
      })
    );
    if (nestedList) pmListItems(nestedList.content ?? [], level + 1, paragraphs);
  }
}

// Converts the editor's document into Word paragraphs matching the firm's
// format: an "H1" becomes a centered title, "H2"-"H4" become numbered
// clause headings (Word auto-numbers them via firmNumberingConfig, so the
// heading text itself must not contain a typed number), plain paragraphs
// are justified body text (including blank ones, to preserve the lawyer's
// spacing), and lists nest one numbering level below whichever heading
// they fall under.
function editorContentToFirmParagraphs(doc: PMNode): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  let titleUsed = false;
  let lastHeadingLevel = -1;

  for (const node of doc.content ?? []) {
    switch (node.type) {
      case "heading": {
        const depth = node.attrs?.level ?? 1;
        if (depth === 1 && !titleUsed) {
          titleUsed = true;
          paragraphs.push(
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 240 },
              children: pmInlineRuns(node.content, { bold: true, size: FIRM_TITLE_SIZE }),
            })
          );
        } else {
          const level = Math.min(Math.max(depth - 2, 0), FIRM_NUMBERING_MAX_LEVEL);
          lastHeadingLevel = level;
          paragraphs.push(
            new Paragraph({
              alignment: AlignmentType.JUSTIFIED,
              spacing: { before: 240, after: FIRM_PARAGRAPH_SPACING_AFTER },
              numbering: { reference: FIRM_NUMBERING_REFERENCE, level },
              children: pmInlineRuns(node.content, { bold: true }),
            })
          );
        }
        break;
      }
      case "paragraph":
        paragraphs.push(
          new Paragraph({
            alignment: AlignmentType.JUSTIFIED,
            spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
            children: pmInlineRuns(node.content),
          })
        );
        break;
      case "bulletList":
      case "orderedList":
        pmListItems(node.content ?? [], Math.min(lastHeadingLevel + 1, FIRM_NUMBERING_MAX_LEVEL), paragraphs);
        break;
      case "horizontalRule":
        paragraphs.push(
          new Paragraph({
            spacing: { before: 120, after: 120 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "999999" } },
          })
        );
        break;
      case "blockquote":
        for (const child of node.content ?? []) {
          if (child.type === "paragraph") {
            paragraphs.push(
              new Paragraph({
                alignment: AlignmentType.JUSTIFIED,
                indent: { left: convertInchesToTwip(0.5) },
                spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
                children: pmInlineRuns(child.content),
              })
            );
          }
        }
        break;
      default:
        break;
    }
  }
  return paragraphs;
}

// Header/footer text matching the firm's own convention (sampled from
// precedent .docx files): matter/doc-type title bar + draft-status notice,
// and a "Page X of Y" footer.
function buildFirmHeader(titleLine: string): Header {
  return new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "999999", space: 4 } },
        children: [
          new TextRun({
            text: titleLine,
            font: FIRM_FONT,
            size: FIRM_HEADER_FOOTER_SIZE,
            color: "595959",
          }),
        ],
      }),
    ],
  });
}

function buildFirmFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: "Page ", font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ children: [PageNumber.CURRENT], font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ text: " of ", font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
        ],
      }),
    ],
  });
}

// Builds the complete firm-styled .docx from the editor's current ProseMirror
// JSON. `headerTitle` is the one-line header bar (matter — type — draft notice).
export function buildFirmDocxBlob(editorDoc: PMNode, headerTitle: string): Promise<Blob> {
  const document = new Document({
    styles: {
      default: {
        document: {
          run: { font: FIRM_FONT, size: FIRM_BODY_SIZE },
        },
      },
    },
    numbering: { config: [firmNumberingConfig] },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
            },
          },
        },
        headers: { default: buildFirmHeader(headerTitle) },
        footers: { default: buildFirmFooter() },
        children: editorContentToFirmParagraphs(editorDoc),
      },
    ],
  });
  return Packer.toBlob(document);
}
