// COPY — do not edit this file. The original is chat-service/sourcePolicy.js, where it
// is used by the chat service and covered by its tests. An edge function
// cannot import from outside supabase/functions, so it is duplicated here
// and tests/sharedCopies.test.js fails if the two ever drift apart. Change
// the original, then copy it here unchanged.

// The same source gate is used by interactive research and statute resolution.
export const OFFICIAL_DOMAINS = ['gov.pk', 'sbp.org.pk', 'nepra.org.pk', 'ogra.org.pk', 'na.gov.pk', 'senate.gov.pk'];
export function officialUrl(value) {
  const url = new URL(value);
  if (url.protocol !== 'https:' || url.username || url.password || (url.port && url.port !== '443') || !OFFICIAL_DOMAINS.some(d => url.hostname === d || url.hostname.endsWith('.' + d))) {
    throw new Error('Source must be an HTTPS document on an approved Pakistani authority domain');
  }
  return url;
}
export async function fetchOfficial(value, { fetcher = fetch, signal, maxBytes = 20 * 1024 * 1024 } = {}) {
  let url = officialUrl(value);
  const timeout = AbortSignal.timeout(45000);
  const requestSignal = signal ? AbortSignal.any([signal, timeout]) : timeout;
  for (let redirects = 0; redirects <= 5; redirects++) {
    const response = await fetcher(url.href, { redirect: 'manual', signal: requestSignal });
    if ([301, 302, 303, 307, 308].includes(response.status)) {
      await response.body?.cancel();
      url = officialUrl(new URL(response.headers.get('location') ?? '', url).href);
      continue;
    }
    if (!response.ok) throw new Error(`Source download failed (${response.status})`);
    if (Number(response.headers.get('content-length') ?? 0) > maxBytes) { await response.body?.cancel(); throw new Error('Source is too large'); }
    if (!response.body) throw new Error('Source is empty');
    const reader = response.body.getReader();
    const chunks = []; let size = 0;
    try {
      while (true) {
        const { value, done } = await reader.read();
        if (done) break;
        size += value.byteLength;
        if (size > maxBytes) throw new Error('Source is too large');
        chunks.push(value);
      }
    } finally { await reader.cancel(); }
    return { blob: new Blob(chunks, { type: response.headers.get('content-type') ?? '' }), url: url.href };
  }
  throw new Error('Too many source redirects');
}
export function sourceIdentityMatches(title, text) {
  const norm = s => s.toLowerCase().replace(/[^a-z0-9]+/g, ' ');
  const words = norm(title).split(' ').filter(w => w.length > 3 && !['the', 'and', 'of', 'pakistan'].includes(w));
  const sample = norm(text.slice(0, 20000));
  const years = title.match(/\b(?:18|19|20)\d{2}\b/g) ?? [];
  return text.trim().length >= 300 && words.length >= 2 && words.every(w => sample.includes(w)) && years.every(y => sample.includes(y));
}
