import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// Two modules are needed both by the chat service on the VM and by an edge
// function: the source policy, which decides what counts as an official
// document and how far a download may go, and the Word structural checks.
// An edge function cannot import from outside supabase/functions, and the
// VM is deployed as a flat directory, so neither can hold the other's file.
// They are duplicated, and this is what keeps the duplicates honest.
for (const name of ['sourcePolicy.js', 'docxChecks.js']) {
  test(`the edge copy of ${name} matches the original exactly`, () => {
    const original = readFileSync(new URL(`../chat-service/${name}`, import.meta.url), 'utf8');
    const copy = readFileSync(new URL(`../supabase/functions/_shared/${name}`, import.meta.url), 'utf8');
    assert.ok(copy.startsWith('// COPY — do not edit this file.'), 'the copy must say that it is one');
    assert.ok(copy.endsWith(original), `supabase/functions/_shared/${name} has drifted from chat-service/${name}`);
  });
}
