import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { marked } from "marked";
import {
  AlignmentType,
  BorderStyle,
  convertInchesToTwip,
  Document,
  Footer,
  Header,
  LevelFormat,
  PageNumber,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import { Sparkles, Send, Save, FileText } from "lucide-react";
import { useMatter } from "@/hooks/useMatters";
import { useDocumentTypes } from "@/hooks/useMatterDocuments";
import { useDraftingInterview, useGenerateDraft } from "@/hooks/useDrafting";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

type Mode = "precedent" | "interview";
interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

// Matches AKLA's own drafting convention (sampled from firm precedent/memo
// .docx files): Arial body text, 1" margins, justified paragraphs with a
// touch of "after" spacing, and legal-style decimal clause numbering
// (1. / 1.1. / 1.1.1.) generated by Word rather than typed by the AI.
const FIRM_FONT = "Arial";
const FIRM_BODY_SIZE = 22; // half-points -> 11pt
const FIRM_TITLE_SIZE = 28; // half-points -> 14pt
const FIRM_HEADER_FOOTER_SIZE = 16; // half-points -> 8pt
const FIRM_LINE_SPACING = { line: 252, lineRule: "auto" as const }; // ~1.05x
const FIRM_PARAGRAPH_SPACING_AFTER = 40; // dxa -> 2pt
const FIRM_NUMBERING_REFERENCE = "firm-clause-numbering";
const FIRM_NUMBERING_MAX_LEVEL = 3;

const firmNumberingConfig = {
  reference: FIRM_NUMBERING_REFERENCE,
  levels: Array.from({ length: FIRM_NUMBERING_MAX_LEVEL + 1 }, (_, level) => ({
    level,
    format: LevelFormat.DECIMAL,
    text: Array.from({ length: level + 1 }, (_, i) => `%${i + 1}`).join(".") + ".",
    alignment: AlignmentType.START,
    style: {
      run: { bold: true },
      paragraph: {
        indent: {
          left: convertInchesToTwip(0.5 + level * 0.25),
          hanging: convertInchesToTwip(0.25),
        },
      },
    },
  })),
};

interface InlineRunStyle {
  bold?: boolean;
  italics?: boolean;
  size?: number;
}

interface PMNode {
  type: string;
  attrs?: Record<string, any>;
  content?: PMNode[];
  text?: string;
  marks?: { type: string }[];
}

// Runs off the live TipTap/ProseMirror editor JSON (editor.getJSON()) rather
// than the original AI markdown, so a lawyer's in-editor edits — including
// blank lines they left in place — are what actually gets exported.
function pmInlineRuns(nodes: PMNode[] | undefined, style: InlineRunStyle = {}): TextRun[] {
  if (!nodes) return [];
  const runs: TextRun[] = [];
  for (const node of nodes) {
    if (node.type === "hardBreak") {
      runs.push(new TextRun({ text: "", break: 1 }));
      continue;
    }
    if (node.type !== "text") continue;
    const marks = node.marks ?? [];
    const nodeStyle: InlineRunStyle = { ...style };
    if (marks.some((m) => m.type === "bold")) nodeStyle.bold = true;
    if (marks.some((m) => m.type === "italic")) nodeStyle.italics = true;
    const isCode = marks.some((m) => m.type === "code");
    runs.push(new TextRun({ text: node.text ?? "", font: isCode ? "Courier New" : FIRM_FONT, ...nodeStyle }));
  }
  return runs;
}

function pmListItems(items: PMNode[], level: number, paragraphs: Paragraph[]) {
  for (const item of items) {
    const nestedList = item.content?.find((n) => n.type === "bulletList" || n.type === "orderedList");
    const ownContent = (item.content ?? []).filter((n) => n.type !== "bulletList" && n.type !== "orderedList");
    const inline = ownContent.flatMap((n) => n.content ?? []);
    paragraphs.push(
      new Paragraph({
        alignment: AlignmentType.JUSTIFIED,
        spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
        numbering: { reference: FIRM_NUMBERING_REFERENCE, level: Math.min(level, FIRM_NUMBERING_MAX_LEVEL) },
        children: pmInlineRuns(inline),
      })
    );
    if (nestedList) pmListItems(nestedList.content ?? [], level + 1, paragraphs);
  }
}

// Converts the editor's document into Word paragraphs matching the firm's
// format: an "H1" becomes a centered title, "H2"-"H4" become numbered
// clause headings (Word auto-numbers them via firmNumberingConfig, so the
// heading text itself must not contain a typed number), plain paragraphs
// are justified body text (including blank ones, to preserve the lawyer's
// spacing), and lists nest one numbering level below whichever heading
// they fall under.
function editorContentToFirmParagraphs(doc: PMNode): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  let titleUsed = false;
  let lastHeadingLevel = -1;

  for (const node of doc.content ?? []) {
    switch (node.type) {
      case "heading": {
        const depth = node.attrs?.level ?? 1;
        if (depth === 1 && !titleUsed) {
          titleUsed = true;
          paragraphs.push(
            new Paragraph({
              alignment: AlignmentType.CENTER,
              spacing: { after: 240 },
              children: pmInlineRuns(node.content, { bold: true, size: FIRM_TITLE_SIZE }),
            })
          );
        } else {
          const level = Math.min(Math.max(depth - 2, 0), FIRM_NUMBERING_MAX_LEVEL);
          lastHeadingLevel = level;
          paragraphs.push(
            new Paragraph({
              alignment: AlignmentType.JUSTIFIED,
              spacing: { before: 240, after: FIRM_PARAGRAPH_SPACING_AFTER },
              numbering: { reference: FIRM_NUMBERING_REFERENCE, level },
              children: pmInlineRuns(node.content, { bold: true }),
            })
          );
        }
        break;
      }
      case "paragraph":
        paragraphs.push(
          new Paragraph({
            alignment: AlignmentType.JUSTIFIED,
            spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
            children: pmInlineRuns(node.content),
          })
        );
        break;
      case "bulletList":
      case "orderedList":
        pmListItems(node.content ?? [], Math.min(lastHeadingLevel + 1, FIRM_NUMBERING_MAX_LEVEL), paragraphs);
        break;
      case "horizontalRule":
        paragraphs.push(
          new Paragraph({
            spacing: { before: 120, after: 120 },
            border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: "999999" } },
          })
        );
        break;
      case "blockquote":
        for (const child of node.content ?? []) {
          if (child.type === "paragraph") {
            paragraphs.push(
              new Paragraph({
                alignment: AlignmentType.JUSTIFIED,
                indent: { left: convertInchesToTwip(0.5) },
                spacing: { ...FIRM_LINE_SPACING, after: FIRM_PARAGRAPH_SPACING_AFTER },
                children: pmInlineRuns(child.content),
              })
            );
          }
        }
        break;
      default:
        break;
    }
  }
  return paragraphs;
}

// Header/footer text matching the firm's own convention (sampled from
// precedent .docx files): matter/doc-type title bar + draft-status notice,
// and a "Page X of Y" footer.
function buildFirmHeader(titleLine: string): Header {
  return new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: "999999", space: 4 } },
        children: [
          new TextRun({
            text: titleLine,
            font: FIRM_FONT,
            size: FIRM_HEADER_FOOTER_SIZE,
            color: "595959",
          }),
        ],
      }),
    ],
  });
}

function buildFirmFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: "Page ", font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ children: [PageNumber.CURRENT], font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ text: " of ", font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], font: FIRM_FONT, size: FIRM_HEADER_FOOTER_SIZE, color: "595959" }),
        ],
      }),
    ],
  });
}

export default function DraftDocumentPage() {
  const { matterId } = useParams<{ matterId: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();

  const { data: matter } = useMatter(matterId);
  const { data: documentTypes } = useDocumentTypes();
  const interviewMutation = useDraftingInterview();
  const draftMutation = useGenerateDraft();

  const [documentTypeId, setDocumentTypeId] = useState<string>("");
  const [mode, setMode] = useState<Mode>("precedent");
  const [started, setStarted] = useState(false);

  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [threadId, setThreadId] = useState<string | undefined>();
  const [isReadyToDraft, setIsReadyToDraft] = useState(false);
  const [chatInput, setChatInput] = useState("");

  const [draft, setDraft] = useState<string | null>(null);
  const [precedentCount, setPrecedentCount] = useState(0);
  const [saving, setSaving] = useState(false);

  const chatEndRef = useRef<HTMLDivElement>(null);

  const documentTypeName = useMemo(
    () => documentTypes?.find((t) => t.id === documentTypeId)?.name ?? "Document",
    [documentTypes, documentTypeId]
  );

  const editor = useEditor({
    extensions: [StarterKit],
    content: "",
  });

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  useEffect(() => {
    if (draft && editor) {
      editor.commands.setContent(marked.parse(draft, { async: false }) as string);
    }
  }, [draft, editor]);

  const handleStart = async () => {
    if (!documentTypeId || !matterId) return;
    setStarted(true);
    if (mode === "interview") {
      const result = await interviewMutation.mutateAsync({ matterId, documentTypeId });
      setThreadId(result.threadId);
      setMessages([{ role: "assistant", content: result.reply }]);
      setIsReadyToDraft(result.isReadyToDraft);
    } else {
      await handleGenerateDraft();
    }
  };

  const handleSendChatMessage = async () => {
    if (!chatInput.trim() || !matterId || !documentTypeId) return;
    const userMessage = chatInput.trim();
    setChatInput("");
    setMessages((prev) => [...prev, { role: "user", content: userMessage }]);
    const result = await interviewMutation.mutateAsync({
      matterId,
      documentTypeId,
      threadId,
      message: userMessage,
    });
    setThreadId(result.threadId);
    setMessages((prev) => [...prev, { role: "assistant", content: result.reply }]);
    setIsReadyToDraft(result.isReadyToDraft);
  };

  const handleGenerateDraft = async () => {
    if (!matterId || !documentTypeId) return;
    try {
      const result = await draftMutation.mutateAsync({
        matterId,
        documentTypeId,
        mode,
        threadId,
      });
      setDraft(result.draft);
      setPrecedentCount(result.precedentCount);
    } catch (err: any) {
      toast({ title: "Draft generation failed", description: err.message, variant: "destructive" });
    }
  };

  const handleSaveAsVersion = async () => {
    if (!editor || !matterId || !documentTypeId) return;
    setSaving(true);
    try {
      const { data: userData } = await supabase.auth.getUser();

      // Find or create the matter_document for this document type
      const { data: existing } = await supabase
        .from("matter_documents")
        .select("id")
        .eq("matter_id", matterId)
        .eq("document_type_id", documentTypeId)
        .limit(1)
        .maybeSingle();

      let matterDocumentId = existing?.id;
      if (!matterDocumentId) {
        const { data: created, error: createError } = await supabase
          .from("matter_documents")
          .insert({
            matter_id: matterId,
            document_type_id: documentTypeId,
            title: `${documentTypeName} (AI draft)`,
            status: "drafting",
            created_by: userData.user?.id,
          })
          .select("id")
          .single();
        if (createError) throw createError;
        matterDocumentId = created.id;
      }

      const { count } = await supabase
        .from("document_versions")
        .select("id", { count: "exact", head: true })
        .eq("matter_document_id", matterDocumentId);
      const nextVersion = (count ?? 0) + 1;

      // Build a .docx from the live editor content (so the lawyer's in-editor
      // edits are what's exported, not the original AI markdown), formatted to
      // match the firm's own drafting convention — see editorContentToFirmParagraphs.
      const paragraphs = editorContentToFirmParagraphs(editor.getJSON() as PMNode);
      const draftDate = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
      const headerTitle = `${matter?.name ?? ""} — ${documentTypeName} — AKLA — Draft, For Internal Purposes Only — ${draftDate}`;

      const document = new Document({
        styles: {
          default: {
            document: {
              run: { font: FIRM_FONT, size: FIRM_BODY_SIZE },
            },
          },
        },
        numbering: { config: [firmNumberingConfig] },
        sections: [
          {
            properties: {
              page: {
                margin: {
                  top: convertInchesToTwip(1),
                  right: convertInchesToTwip(1),
                  bottom: convertInchesToTwip(1),
                  left: convertInchesToTwip(1),
                },
              },
            },
            headers: { default: buildFirmHeader(headerTitle) },
            footers: { default: buildFirmFooter() },
            children: paragraphs,
          },
        ],
      });
      const blob = await Packer.toBlob(document);
      const fileName = `${documentTypeName.replace(/\s+/g, "-")}-v${nextVersion}.docx`;
      const storagePath = `${matterId}/${matterDocumentId}/v${nextVersion}-${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from("matter-documents")
        .upload(storagePath, blob, {
          contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        });
      if (uploadError) throw uploadError;

      const { error: versionError } = await supabase.from("document_versions").insert({
        matter_document_id: matterDocumentId,
        version_number: nextVersion,
        storage_path: storagePath,
        is_ai_generated: true,
        uploaded_by: userData.user?.id,
      });
      if (versionError) throw versionError;

      toast({ title: "Draft saved as a document version" });
      navigate(`/matters/${matterId}`);
    } catch (err: any) {
      toast({ title: "Failed to save draft", description: err.message, variant: "destructive" });
    } finally {
      setSaving(false);
    }
  };

  if (!matterId) return null;

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-semibold flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          Draft with AI
        </h1>
        <p className="text-muted-foreground">{matter?.name}</p>
      </div>

      {!started ? (
        <Card>
          <CardContent className="pt-6 space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Document type</label>
              <Select value={documentTypeId} onValueChange={setDocumentTypeId}>
                <SelectTrigger>
                  <SelectValue placeholder="Select a document type" />
                </SelectTrigger>
                <SelectContent>
                  {documentTypes?.map((type) => (
                    <SelectItem key={type.id} value={type.id}>
                      {type.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">How should the draft be built?</label>
              <Tabs value={mode} onValueChange={(v) => setMode(v as Mode)}>
                <TabsList>
                  <TabsTrigger value="precedent">From precedent</TabsTrigger>
                  <TabsTrigger value="interview">Guided interview</TabsTrigger>
                </TabsList>
              </Tabs>
              <p className="text-xs text-muted-foreground">
                {mode === "precedent"
                  ? "Drafts from the firm's past agreements of this type, plus known matter parties. Best when close precedent exists."
                  : "Claude asks you the key commercial terms one at a time, then drafts from your answers. Best when no close precedent exists yet."}
              </p>
            </div>

            <Button onClick={handleStart} disabled={!documentTypeId}>
              {mode === "precedent" ? "Generate Draft" : "Start Interview"}
            </Button>
          </CardContent>
        </Card>
      ) : (
        <>
          {mode === "interview" && !draft && (
            <Card>
              <CardContent className="pt-6 space-y-4">
                <div className="space-y-3 max-h-96 overflow-y-auto">
                  {messages.map((m, i) => (
                    <div
                      key={i}
                      className={cn(
                        "rounded-lg px-3 py-2 text-sm max-w-[85%]",
                        m.role === "assistant"
                          ? "bg-muted"
                          : "bg-primary text-primary-foreground ml-auto"
                      )}
                    >
                      {m.content}
                    </div>
                  ))}
                  <div ref={chatEndRef} />
                </div>
                <div className="flex gap-2">
                  <Input
                    placeholder="Type your answer…"
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && handleSendChatMessage()}
                    disabled={interviewMutation.isPending}
                  />
                  <Button
                    size="icon"
                    onClick={handleSendChatMessage}
                    disabled={!chatInput.trim() || interviewMutation.isPending}
                  >
                    <Send className="h-4 w-4" />
                  </Button>
                </div>
                <Button
                  variant={isReadyToDraft ? "default" : "outline"}
                  onClick={handleGenerateDraft}
                  disabled={draftMutation.isPending}
                >
                  <FileText className="h-4 w-4 mr-2" />
                  {isReadyToDraft ? "Generate Draft" : "Draft Now Anyway"}
                </Button>
              </CardContent>
            </Card>
          )}

          {draftMutation.isPending && (
            <p className="text-muted-foreground">Drafting — this can take a moment…</p>
          )}

          {draft && (
            <Card>
              <CardContent className="pt-6 space-y-4">
                <p className="text-xs text-muted-foreground">
                  {precedentCount > 0
                    ? `Drafted using ${precedentCount} precedent document${precedentCount === 1 ? "" : "s"} of this type.`
                    : "No precedent of this type in the library yet — drafted from standard practice."}
                  {" "}Review and edit before saving — this is a first draft, not final.
                </p>
                <div className="border rounded-md p-4 prose prose-sm max-w-none min-h-[400px]">
                  <EditorContent editor={editor} />
                </div>
                <Button onClick={handleSaveAsVersion} disabled={saving}>
                  <Save className="h-4 w-4 mr-2" />
                  Save as Document Version
                </Button>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}
